Downgrade very common log warnings
These two logs, in particular:

    Server could not verify regular token!

    Error: connection could not be created

fire incredibly often in storage server (which, at default log level,
has quic at warning level), most likely because of expired (or sleeping)
incoming quic connections.

These are neither problems to be fixed, nor problems that even can be
fixed, so warning seems too high for them and so this downgrades them to
info level.